apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: c401d3lfy-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:c6c66eaeb162cd1b81be022907f970249131ca6f@sha256:7ff08aa8593aec3ca4cd85ac386dcf3ccd798ae42d44a805001f1bb95b9b78a8
          name: container-image
